[hypervisors]
ken-optiplex-7010 ansible_host=100.117.128.67

[workstations]
ken-lenovo-ideapad-110-15isk ansible_host=100.109.2.114

[enterprise_nodes:children]
rhel_nodes
alma_nodes
rocky_nodes

[rhel_nodes]
rhel-node1 ansible_host=100.126.26.113

[alma_nodes]
almalinux10 ansible_host=100.67.104.107

[rocky_nodes]
the-rock ansible_host=100.107.171.99

[all:vars]
ansible_user=kmorgan
ansible_ssh_private_key_file=~/.ssh/id_ed25519
